Library/Models/Clients.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Library.Models
{
    public class Clients
    {
        [Key] public int ClientId { get; set; }
        [Column(TypeName = "varchar(50)")]
        [RegularExpression(@"^[A-Z][a-z]{1,49}$", ErrorMessage = "Wrong name")]
        public string FirstName { get; set; }
        [Column(TypeName = "varchar(50)")]
        [RegularExpression(@"^[A-Z][a-z]{1,49}$", ErrorMessage = "Wrong surname")]
        public string Surname { get; set; }

    }
}

Library/Controllers/BooksController.cs
using Library.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class BooksController : Controller
    {
        private readonly BooksDbContext _context;
        public BooksController(BooksDbContext context)
        {
            _context = context;
        }
        public ActionResult Books()
        {
            var Books = _context.Books.Include(f => f.Category).ToList();
            return View(Books);
        }

        // GET: BooksController
        public ActionResult Index()
        {
            var Books = _context.Books.Include(f => f.Category).ToList();
            return View(Books);
        }

        // GET: BooksController/Details/5
        public ActionResult Details(int id)
        {
            var book = _context.Books
                    .Include(b => b.Category)
                    .FirstOrDefault(b => b.Id == id);
            return View(book);
           //return View();
        }

        public ActionResult DetailsBooks(int id)
        {
            var book = _context.Books
                    .Include(b => b.Category)
                    .FirstOrDefault(b => b.Id == id);
            return View(book);
            //return View();
        }

        // GET: BooksController/Create
        public ActionResult Create()
        {
            // Pobierz kategorie z bazy danych
            var kategorie = _context.Category.ToList();
            // Utwórz SelectList i przekaż ją do ViewBag
            ViewBag.CategoryId = new SelectList(kategorie, "Id", "Name");
            return View();

        }

        // POST: BooksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Title,EditionYear,Description,CategoryId")] Books book)
        {
            try
            {
                _context.Books.Add(book);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var categories = _context.Category.ToList();
                ViewBag.CategoryId = new SelectList(categories, "Id", "Name");
                return View(book);
            }
        }

        // GET: BooksController/Edit/5
        public ActionResult Edit(int id)
        {
            var book = _context.Books
            .Include(b => b.Category)
            .FirstOrDefault(b => b.Id == id);
            return View(book);
        }

        // POST: BooksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Books updatedBook)
        {
            var book = _context.Books
            .Include(b => b.Category)
            .FirstOrDefault(b => b.Id == id);

            book.Title = updatedBook.Title;
            book.EditionYear = updatedBook.EditionYear;
            book.Description = updatedBook.Description;

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        // GET: BooksController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BooksController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Library/Controllers/CategoryController.cs
using Library.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CopyAnalysis;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class CategoryController : Controller
    {
        private readonly BooksDbContext _context;
        public CategoryController(BooksDbContext context)
        {
            _context = context;
        }
        // GET: CategoryController
        public ActionResult Index()
        {
            var Copies = _context.Category.ToList();
            return View(Copies);
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            var categories = _context.Category.ToList();
            // Utwórz SelectList i przekaż ją do ViewBag
            ViewBag.BookId = new SelectList(categories, "Id", "Title");
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category updatedCategory)
        {
            try
            {
                Category category = new Category();
                category.Name = updatedCategory.Name;
                _context.Category.Add(category);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(updatedCategory);
            }
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            var category = _context.Category
            .FirstOrDefault(b => b.Id == id);
            return View(category);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,  Category updatedCategory)
        {
            var category = _context.Category
            .FirstOrDefault(b => b.Id == id);

            category.Name = updatedCategory.Name;


            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Library/Controllers/ClientsController.cs
using Library.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class ClientsController : Controller
    {
        private readonly BooksDbContext _context;
        public ClientsController(BooksDbContext context)
        {
            _context = context;
        }
        // GET: ClientsController
        public ActionResult Index()
        {
            var Clients = _context.Clients.ToList();
            return View(Clients);
        }

        // GET: ClientsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClientsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Clients updatedClient)
        {
            try
            {
                Clients client = new Clients();
                client.FirstName = updatedClient.FirstName;
                client.Surname = updatedClient.Surname;

                _context.Clients.Add(client);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(updatedClient);
            }
        }

        // GET: ClientsController/Edit/5
        public ActionResult Edit(int id)
        {
            var client = _context.Clients
            .FirstOrDefault(b => b.ClientId == id);
            return View(client);
        }

        // POST: ClientsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Clients updatedClient)
        {
            var client = _context.Clients
            .FirstOrDefault(b => b.ClientId == id);

            client.FirstName = updatedClient.FirstName;
            client.Surname = updatedClient.Surname;


            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: ClientsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClientsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Library/Controllers/CopiesController.cs
using Library.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CopyAnalysis;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class CopiesController : Controller
    {
        private readonly BooksDbContext _context;
        public CopiesController(BooksDbContext context)
        {
            _context = context;
        }
        // GET: CopiesController
        public ActionResult Index()
        {
            var Copies = _context.Copies.OrderBy(c => c.BookId).Include(C => C.Client).Include(b => b.Book).ToList();
            return View(Copies);
        }

        // GET: CopiesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CopiesController/Create
        public ActionResult Create()
        {
            var books = _context.Books.ToList();
            // Utwórz SelectList i przekaż ją do ViewBag
            ViewBag.BookId = new SelectList(books, "Id", "Title");
            return View();
        }

        // POST: CopiesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Copies updatedCopy)
        {
            try
            {
                Copies copy = new Copies();
                copy.BookId = updatedCopy.BookId;
                copy.IsAvailable = true;
                copy.ClientId = 1;
                _context.Copies.Add(copy);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var books = _context.Books.ToList();
                // Utwórz SelectList i przekaż ją do ViewBag
                ViewBag.BookId = new SelectList(books, "Id", "Title");
                return View(updatedCopy);
            }
        }

        // GET: CopiesController/Edit/5
        public ActionResult Edit(int id)
        {
            var copy = _context.Copies
            .FirstOrDefault(b => b.CopyId == id);

            var books = _context.Books.ToList();
            ViewBag.BookId = new SelectList(books, "Id", "Title");
            var clients = _context.Clients.ToList();
            ViewBag.ClientId = new SelectList(clients, "ClientId", "FirstName");

            return View(copy);
        }

        // POST: BooksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Copies updatedCopy)
        {


            var books = _context.Books.ToList();
            ViewBag.BookId = new SelectList(books, "Id", "Title");
            var clients = _context.Clients.ToList();
            ViewBag.ClientId = new SelectList(clients, "ClientId", "FirstName");

            var copy = _context.Copies
            .FirstOrDefault(b => b.CopyId == id);

            copy.BookId = updatedCopy.BookId;
            copy.IsAvailable = updatedCopy.IsAvailable;
            if(!updatedCopy.IsAvailable)
                copy.ClientId = updatedCopy.ClientId;
            else
                copy.ClientId = 1;


            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }


        // GET: CopiesController/Delete/5
        public ActionResult Delete(int id)
        {
            var book = _context.Copies
            .FirstOrDefault(b => b.CopyId == id);
            return View(book);
        }

        // POST: CopiesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                var copy = _context.Copies
                .FirstOrDefault(b => b.CopyId == id);
                _context.Copies.Remove(copy);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Library/Views/Clients/Create.cshtml
@model Library.Models.Clients

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Clients</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Clients/Edit.cshtml
@model Library.Models.Clients

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Clients</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Clients/Index.cshtml
@model IEnumerable<Library.Models.Clients>

@{
    ViewData["Title"] = "Clients";
}

<h1>Clients</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-area="" asp-controller="Books" asp-action="Index">Books</a>
    <a asp-area="" asp-controller="Copies" asp-action="Index">Copies</a>
    <a asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ClientId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClientId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id=item.ClientId})
            </td>
        </tr>
}
    </tbody>
</table>