Library/Controllers/BooksController.cs
using Library.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class BooksController : Controller
    {
        private readonly BooksDbContext _context;
        public BooksController(BooksDbContext context)
        {
            _context = context;
        }
        public ActionResult Books()
        {
            var Books = _context.Books.Include(f => f.Category).ToList();
            return View(Books);
        }

        // GET: BooksController
        public ActionResult Index()
        {
            var Books = _context.Books.Include(f => f.Category).ToList();
            return View(Books);
        }

        // GET: BooksController/Details/5
        public ActionResult Details(int id)
        {
            var book = _context.Books
                    .Include(b => b.Category)
                    .FirstOrDefault(b => b.Id == id);
            return View(book);
           //return View();
        }

        public ActionResult DetailsBooks(int id)
        {
            var book = _context.Books
                    .Include(b => b.Category)
                    .FirstOrDefault(b => b.Id == id);
            return View(book);
            //return View();
        }

        // GET: BooksController/Create
        public ActionResult Create()
        {
            // Pobierz kategorie z bazy danych
            var kategorie = _context.Category.ToList();
            // Utwórz SelectList i przekaż ją do ViewBag
            ViewBag.CategoryId = new SelectList(kategorie, "Id", "Name");
            return View();

        }

        // POST: BooksController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Title,EditionYear,Description,CategoryId")] Books book)
        {
            try
            {
                _context.Books.Add(book);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var categories = _context.Category.ToList();
                ViewBag.CategoryId = new SelectList(categories, "Id", "Name");
                return View(book);
            }
        }

        // GET: BooksController/Edit/5
        public ActionResult Edit(int id)
        {
            var book = _context.Books
            .Include(b => b.Category)
            .FirstOrDefault(b => b.Id == id);
            return View(book);
        }

        // POST: BooksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Books updatedBook)
        {
            var book = _context.Books
            .Include(b => b.Category)
            .FirstOrDefault(b => b.Id == id);

            book.Title = updatedBook.Title;
            book.EditionYear = updatedBook.EditionYear;
            book.Description = updatedBook.Description;

            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        // GET: BooksController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BooksController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Library/Controllers/CategoryController.cs
using Library.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CopyAnalysis;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class CategoryController : Controller
    {
        private readonly BooksDbContext _context;
        public CategoryController(BooksDbContext context)
        {
            _context = context;
        }
        // GET: CategoryController
        public ActionResult Index()
        {
            var Copies = _context.Category.ToList();
            return View(Copies);
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            var categories = _context.Category.ToList();
            // Utwórz SelectList i przekaż ją do ViewBag
            ViewBag.BookId = new SelectList(categories, "Id", "Title");
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category updatedCategory)
        {
            try
            {
                Category category = new Category();
                category.Name = updatedCategory.Name;
                _context.Category.Add(category);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(updatedCategory);
            }
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            var category = _context.Category
            .FirstOrDefault(b => b.Id == id);
            return View(category);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id,  Category updatedCategory)
        {
            var category = _context.Category
            .FirstOrDefault(b => b.Id == id);

            category.Name = updatedCategory.Name;


            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Library/Controllers/ClientsController.cs
using Library.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class ClientsController : Controller
    {
        private readonly BooksDbContext _context;
        public ClientsController(BooksDbContext context)
        {
            _context = context;
        }
        // GET: ClientsController
        public ActionResult Index()
        {
            var Clients = _context.Clients.ToList();
            return View(Clients);
        }

        // GET: ClientsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ClientsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClientsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Clients updatedClient)
        {
            try
            {
                Clients client = new Clients();
                client.FirstName = updatedClient.FirstName;
                client.Surname = updatedClient.Surname;

                _context.Clients.Add(client);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(updatedClient);
            }
        }

        // GET: ClientsController/Edit/5
        public ActionResult Edit(int id)
        {
            var client = _context.Clients
            .FirstOrDefault(b => b.ClientId == id);
            return View(client);
        }

        // POST: ClientsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Clients updatedClient)
        {
            var client = _context.Clients
            .FirstOrDefault(b => b.ClientId == id);

            client.FirstName = updatedClient.FirstName;
            client.Surname = updatedClient.Surname;


            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: ClientsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClientsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Library/Controllers/CopiesController.cs
using Library.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow.CopyAnalysis;
using Microsoft.EntityFrameworkCore;

namespace Library.Controllers
{
    public class CopiesController : Controller
    {
        private readonly BooksDbContext _context;
        public CopiesController(BooksDbContext context)
        {
            _context = context;
        }
        // GET: CopiesController
        public ActionResult Index()
        {
            var Copies = _context.Copies.OrderBy(c => c.BookId).Include(C => C.Client).Include(b => b.Book).ToList();
            return View(Copies);
        }

        // GET: CopiesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CopiesController/Create
        public ActionResult Create()
        {
            var books = _context.Books.ToList();
            // Utwórz SelectList i przekaż ją do ViewBag
            ViewBag.BookId = new SelectList(books, "Id", "Title");
            return View();
        }

        // POST: CopiesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Copies updatedCopy)
        {
            try
            {
                Copies copy = new Copies();
                copy.BookId = updatedCopy.BookId;
                copy.IsAvailable = true;
                copy.ClientId = 1;
                _context.Copies.Add(copy);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                var books = _context.Books.ToList();
                // Utwórz SelectList i przekaż ją do ViewBag
                ViewBag.BookId = new SelectList(books, "Id", "Title");
                return View(updatedCopy);
            }
        }

        // GET: CopiesController/Edit/5
        public ActionResult Edit(int id)
        {
            var copy = _context.Copies
            .FirstOrDefault(b => b.CopyId == id);

            var books = _context.Books.ToList();
            ViewBag.BookId = new SelectList(books, "Id", "Title");
            var clients = _context.Clients.ToList();
            ViewBag.ClientId = new SelectList(clients, "ClientId", "FirstName");

            return View(copy);
        }

        // POST: BooksController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Copies updatedCopy)
        {


            var books = _context.Books.ToList();
            ViewBag.BookId = new SelectList(books, "Id", "Title");
            var clients = _context.Clients.ToList();
            ViewBag.ClientId = new SelectList(clients, "ClientId", "FirstName");

            var copy = _context.Copies
            .FirstOrDefault(b => b.CopyId == id);

            copy.BookId = updatedCopy.BookId;
            copy.IsAvailable = updatedCopy.IsAvailable;
            if(!updatedCopy.IsAvailable)
                copy.ClientId = updatedCopy.ClientId;
            else
                copy.ClientId = 1;


            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }


        // GET: CopiesController/Delete/5
        public ActionResult Delete(int id)
        {
            var book = _context.Copies
            .FirstOrDefault(b => b.CopyId == id);
            return View(book);
        }

        // POST: CopiesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                var copy = _context.Copies
                .FirstOrDefault(b => b.CopyId == id);
                _context.Copies.Remove(copy);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Library/Views/Copies/Create.cshtml
@model Library.Models.Copies

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Copy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label">Book ID</label>
                <input asp-for="BookId" class="form-control" />
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
@*             <div class="form-group">
                <label asp-for="BookId" class="control-label">Book ID</label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId" />
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div> *@
@*             <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Library/Views/Copies/Delete.cshtml
@model Library.Models.Copies

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Copies</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CopyId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CopyId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsAvailable)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Library/Views/Copies/Edit.cshtml
@model Library.Models.Copies

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Copy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label">Book</label>
                <select asp-for="BookId" class="form-control" asp-items="ViewBag.BookId"></select>
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input id="IsAvailable" class="form-check-input" asp-for="IsAvailable" /> @Html.DisplayNameFor(model => model.IsAvailable)
                </label>
            </div>
            <div id="ClientIdGroup" class="form-group">
                <label asp-for="ClientId" class="control-label">Client</label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        // Function to show/hide the ClientId dropdown
        function toggleClientIdVisibility() {
            const isAvailable = document.getElementById('IsAvailable').checked;
            const clientIdGroup = document.getElementById('ClientIdGroup');
            clientIdGroup.style.display = isAvailable ? 'none' : 'block'; // Hide if IsAvailable is true
        }

        // Attach event listener to the IsAvailable checkbox
        document.getElementById('IsAvailable').addEventListener('change', toggleClientIdVisibility);

        // Run the function on page load to set the initial state
        toggleClientIdVisibility();
    </script>
}

Library/Views/Copies/Index.cshtml
@model IEnumerable<Library.Models.Copies>

@{
    ViewData["Title"] = "Copies";
}

<h1>Copies</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-area="" asp-controller="Books" asp-action="Index">Books</a>
    <a asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
    <a asp-area="" asp-controller="Clients" asp-action="Index">Clients</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CopyId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookId)
            </th>
            <th>
                BookTitle
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsAvailable)
            </th>
            <th>
                ClientName
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CopyId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookId)
            </td>
             <td>
                 @Html.DisplayFor(modelItem => item.Book.Title)
             </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsAvailable)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Client.FirstName)
                </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.CopyId}) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CopyId })
            </td>
        </tr>
}
    </tbody>
</table>